# Generated by Django 3.0.4 on 2020-03-19 21:06

from django.db import migrations
import csv
import datetime

GLOBAL_COVID_19_CSV_PATH = "../data/Global/global_data_4_21.csv"
US_STATES_COVID_19_CSV_PATH = "../data/Global/US_States/us_states_data_4_21.csv"


def load_covid19_data(apps, schema_editor):
    Area = apps.get_model('model_api', 'Area')
    Covid19DataPoint = apps.get_model('model_api', 'Covid19DataPoint')

    # Country level data.
    with open(GLOBAL_COVID_19_CSV_PATH) as f:
        reader = csv.reader(f)
        header = next(reader, None)

        for row in reader:
            country = row[1]

            # Write new infection area to database.
            area = Area(state='', country=country)
            area.save()

            for i in range(2, len(header)):
                date = header[i]
                val = int(float(row[i]))

                # Write new infection data to database.
                covid19_data_point = Covid19DataPoint(area=area, date=date, val=val)
                covid19_data_point.save()


    # US state-level data.
    with open(US_STATES_COVID_19_CSV_PATH) as f:
        reader = csv.reader(f)
        header = next(reader, None)

        for row in reader:
            state = row[1]
            country = 'US'

            # Write new infection area to database.
            area = Area(state=state, country=country)
            area.save()

            for i in range(2, len(header)):
                raw_date = header[i]
                date = datetime.datetime(header[i])
                val = int(float(row[i]))

                # Write new infection data to database.
                covid19_data_point = Covid19DataPoint(area=area, date=date, val=val)
                covid19_data_point.save()


def delete_covid19_data(apps, schema_editor):
    Area = apps.get_model('model_api', 'Area')
    Covid19DataPoint = apps.get_model('model_api', 'Covid19DataPoint')

    # Clear any previously-existing data.
    Area.objects.all().delete()
    Covid19DataPoint.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('model_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_covid19_data, delete_covid19_data),
    ]
