# Generated by Django 3.0.4 on 2020-03-31 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_api', '0002_load_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19CumulativeDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_api.Area')),
                ('data_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_api.Covid19DataPoint')),
            ],
        ),
    ]
