# Generated by Django 3.0.4 on 2020-03-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_api', '0004_fill_cumulative_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='iso_2',
            field=models.CharField(default='', max_length=10),
        ),
    ]
