# Generated by Django 3.0.4 on 2020-05-02 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_api', '0006_load_iso_2_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('social_distancing', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Covid19PredictionDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('val', models.PositiveIntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_api.Area')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_api.Covid19Model')),
            ],
        ),
    ]
