# Generated by Django 3.0.4 on 2020-04-12 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_api', '0006_load_iso_2_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19ReleasedPredictionDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('val', models.PositiveIntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_api.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Covid19QuarantinePredictionDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('val', models.PositiveIntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_api.Area')),
            ],
        ),
    ]
