# Generated by Django 3.0.4 on 2020-07-14 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_api', '0011_load_quaratine_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRFScoreDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('val', models.FloatField()),
                ('conf', models.FloatField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_api.Area')),
            ],
        ),
    ]
