# Generated by Django 3.0.4 on 2020-05-02 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_api', '0006_load_iso_2_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19Model',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name = 'Covid19InfectionModel',
            fields=[
                ('covid19model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model_api.Covid19Model')),
            ],
            bases=('model_api.covid19model',),
        ),
        migrations.CreateModel(
            name = 'Covid19DeathModel',
            fields=[
                ('covid19model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model_api.Covid19Model')),
            ],
            bases=('model_api.covid19model',),
        ),
        migrations.CreateModel(
            name='Covid19PredictionDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_distancing', models.BooleanField()),
                ('date', models.DateField()),
                ('val', models.PositiveIntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_api.Area')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_api.Covid19Model')),
            ],
        ),
    ]
